stages:
- name: test1
  steps:
  - runScriptConfig:
      image: ubuntu:18.04
      shellScript: |-
        apt-get update
        apt-get install -y nodejs npm
        npm install -g vamp-cli-ee
        sleep 10
        $(which vamp) -V
notification: {}
